### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [8, 64000] at entry 0 and [8, 205052] at entry 7

### ISSUE THREAD

**Issue by wpupup** [felixfuyihui/AISHELL-4#3]
I have got this error when train the model

Traceback (most recent call last):
  File "steps/run_realmask.py", line 402, in <module>
    main()
  File "steps/run_realmask.py", line 277, in main
    train(model, device, writer)
  File "steps/run_realmask.py", line 88, in train
    val_loss = validation(model, -1, lr, device)
  File "steps/run_realmask.py", line 209, in validation
    for idx, data in enumerate(dataloader):
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.

Original Traceback (most recent call last):
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [8, 64000] at entry 0 and [8, 205052] at entry 7

**Comment by wpupup** [comment]
> I have got this error when train the model
> 
> Traceback (most recent call last):
> File "steps/run_realmask.py", line 402, in
> main()
> File "steps/run_realmask.py", line 277, in main
> train(model, device, writer)
> File "steps/run_realmask.py", line 88, in train
> val_loss = validation(model, -1, lr, device)
> File "steps/run_realmask.py", line 209, in validation
> for idx, data in enumerate(dataloader):
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in **next**
> data = self._next_data()
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
> return self._process_data(data)
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
> data.reraise()
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
> raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> 
> Original Traceback (most recent call last):
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
> return self.collate_fn(data)
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
> return {key: default_collate([d[key] for d in batch]) for key in elem}
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in
> return {key: default_collate([d[key] for d in batch]) for key in elem}
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
> return default_collate([torch.as_tensor(b) for b in batch])
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
> return torch.stack(batch, 0, out=out)
> RuntimeError: stack expects each tensor to be equal size, but got [8, 64000] at entry 0 and [8, 205052] at entry 7

**Comment by wpupup** [comment]
> I have got this error when train the model
> 
> Traceback (most recent call last):
> File "steps/run_realmask.py", line 402, in
> main()
> File "steps/run_realmask.py", line 277, in main
> train(model, device, writer)
> File "steps/run_realmask.py", line 88, in train
> val_loss = validation(model, -1, lr, device)
> File "steps/run_realmask.py", line 209, in validation
> for idx, data in enumerate(dataloader):
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in **next**
> data = self._next_data()
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
> return self._process_data(data)
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
> data.reraise()
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
> raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> 
> Original Traceback (most recent call last):
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
> return self.collate_fn(data)
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
> return {key: default_collate([d[key] for d in batch]) for key in elem}
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in
> return {key: default_collate([d[key] for d in batch]) for key in elem}
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
> return default_collate([torch.as_tensor(b) for b in batch])
> File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
> return torch.stack(batch, 0, out=out)
> RuntimeError: stack expects each tensor to be equal size, but got [8, 64000] at entry 0 and [8, 205052] at entry 7

**Comment by felixfuyihui** [comment]
Hello
I've never met this error before. Please check all data you generated are in 8 channels. And also make sure that the wavlength in 'utt2dur' is absolutely right. (The dur means the number of samples).













At 2021-07-19 17:38:41, "wpupup" ***@***.***> wrote:

I have got this error when train the model

Traceback (most recent call last):
File "steps/run_realmask.py", line 402, in
main()
File "steps/run_realmask.py", line 277, in main
train(model, device, writer)
File "steps/run_realmask.py", line 88, in train
val_loss = validation(model, -1, lr, device)
File "steps/run_realmask.py", line 209, in validation
for idx, data in enumerate(dataloader):
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in next
data = self._next_data()
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
return self._process_data(data)
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
data.reraise()
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.

Original Traceback (most recent call last):
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
data = fetcher.fetch(index)
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
return self.collate_fn(data)
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
return {key: default_collate([d[key] for d in batch]) for key in elem}
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in
return {key: default_collate([d[key] for d in batch]) for key in elem}
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
return default_collate([torch.as_tensor(b) for b in batch])
File "/home/pingan/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [8, 64000] at entry 0 and [8, 205052] at entry 7

**Comment by SouppuoS** [comment]
> Hello I've never met this error before. Please check all data you generated are in 8 channels. And also make sure that the wavlength in 'utt2dur' is absolutely right. (The dur means the number of samples).

Besides, I found the order of wavs in `.scp` should be the same as `utt2dur`.
So if you use the script under `sd` folder to generate `.scp`, an additional sort is needed.
